### ISSUE TITLE
Double title

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#111]
Here you see the title two times. 

Is this the way you want it or should I remove it? 

![Screenshot_20221007-165836~2.png](https://user-images.githubusercontent.com/720573/194585235-5f5488de-5ecd-4a8f-9dfe-f4acbb1e4249.png)

**Comment by CrazyMarvin** [comment]
Thanks for noticing.
Please remove it.
You may check the [mockups](https://www.figma.com/file/9Fk92SQVItIwAjVfsakopo/).

**Comment by CrazyMarvin** [comment]
It would be great if you could fix #98 too.
Arafaat is busy at the moment.
