### ISSUE TITLE
Keyword can deleted 

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#114]
How can i delete an old Keywords from the App an the translate.
The keyword apache can be deleted

https://hosted.weblate.org/translate/vacation-days/vacation-days/de/?checksum=a8a58bfb1ce733f7

**Comment by CrazyMarvin** [comment]
Why can it be deleted?
Is it not used anymore?

**Comment by amarradi** [comment]
Yes this string is old and can be deleted. It was the first version text on
the about activity.

Mein Krebstagebuch  https://www.marcusradisch.de

CrazyMarvin ***@***.***> schrieb am Fr., 7. Okt. 2022, 22:09:

**Comment by CrazyMarvin** [comment]
When you delete the string in the strings.xml (don't forget the already translated strings.xml files) it gets deleted on Weblate too.

**Comment by CrazyMarvin** [comment]
The `apache` string should be used in the About page next to the version. May you please add it again?
It should say `9.0 Beta - Apache License 2.0`. The version (e.g. `9.0`) is generated dynamically and `Beta - Apache License 2.0` is static.

![photo_5917743117845510566_y](https://user-images.githubusercontent.com/15004217/194853947-7817796c-6886-4ecf-aa41-ced74c99171e.jpg)

**Comment by amarradi** [comment]
Yes i Change it. How many more version iterations do you want to do before
a non-beta?

Mein Krebstagebuch  https://www.marcusradisch.de

CrazyMarvin ***@***.***> schrieb am Mo., 10. Okt. 2022, 13:17:

**Comment by CrazyMarvin** [comment]
> Yes i Change it. How many more version iterations do you want to do before a non-beta?

I would like to test the backup and import feature more and fix most of the existing issues first.
