### ISSUE TITLE
No Daycount validation 

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#115]
![Screenshot_20221009-211038~2.png](https://user-images.githubusercontent.com/720573/194775426-cbe9962b-d988-48f1-b15a-f9629cc8a9ab.png)

I can currently allocate more days than I have available.

**Comment by CrazyMarvin** [comment]
I am not sure how Vacation Days should handle this behaviour. 🤔

It is possible to schedule more vacation days than are available. These will then be deducted in the next year. It is not a standard, but when an employee needs more vacation days most employers allow this.

**Comment by CrazyMarvin** [comment]
We will keep the behaviour as is.

**Comment by amarradi** [comment]
Maybe an if condition would be good, comparing whether the selected number is less than or equal to the vacation days. And then show an info box saying that the maximum number has been reached. If you do not check the vacation days entered somehow, you can also remove the vacation days entry.

**Comment by amarradi** [comment]
I'll try to implement it and give you a pull requests

**Comment by CrazyMarvin** [comment]
> Maybe an if condition would be good, comparing whether the selected number is less than or equal to the vacation days. And then show an info box saying that the maximum number has been reached. If you do not check the vacation days entered somehow, you can also remove the vacation days entry.

I would be fine with an info box. 👍
But it should be possible to go over the quota and see something like -4.
