### ISSUE TITLE
Hosted Weblate Integration

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/VacationDays#2]

**Comment by CrazyMarvin** [comment]
![end](https://user-images.githubusercontent.com/15004217/117357458-41bab200-aeb5-11eb-81e4-66edf3fd76b0.PNG)

I cannot add this project. Do you have any idea, @comradekingu?

**Comment by comradekingu** [comment]
@CrazyMarvin Maybe you need a new plan for the new project?
If you remove the CoC and add "kingu" I can try to help :)

**Comment by CrazyMarvin** [comment]
What do you mean with _CoC_?  🤔

**Comment by CrazyMarvin** [comment]
If you mean the Contributor Covenant Code of Conduct, I am open for alternative ideas.

**Comment by comradekingu** [comment]
Remove, and replace with

```
Welcome to the VacationDays community

Accept and offer criticism constructively. Let anyone have their desired privacy.
Settle differences within these boundaries.
Finding yourselves unable to do so, e-mail Marvin@e-maildomain.org, answered by CrazyMarvin, the project maintainer.
```
as CONTACT.md

**Comment by CrazyMarvin** [comment]
Thanks! I opened a new plan and added Vacation Days to it. 👌
