### ISSUE TITLE
Missing strings

### ISSUE THREAD

**Issue by comradekingu** [Crazy-Marvin/VacationDays#22]
@CrazyMarvin 
Added screenshots https://hosted.weblate.org/screenshots/vacation-days/vacation-days/
but a lot of those strings aren't in
https://hosted.weblate.org/zen/vacation-days/vacation-days/en/?q=

Only the ones in https://github.com/Crazy-Marvin/VacationDays/blob/development/app/src/main/res/values/strings.xml are shown, and everything in
https://github.com/Crazy-Marvin/VacationDays/blob/aa33f7df3605b69a1d1c6638abd561311cdcbef2/app/src/main/res/layout/activity_settings.xml
is missing.

Can those be added to the regular strings.xml?

**Comment by CrazyMarvin** [comment]
I will ask the Weblate support to have a look at the configuration.

**Comment by comradekingu** [comment]
It is no surprise it doesn't work when there is only "app/src/main/res/values-*/strings.txt" in https://hosted.weblate.org/settings/vacation-days/vacation-days/#files

I am thinking Android won't pick up app/src/main/res/layout/nb_NO/activity_settings.xml etc.

If the content and pointers to activity_settings.xml was in strings.xml the setup would work.

**Comment by CrazyMarvin** [comment]
We will put all strings into /app/src/main/res/values/[strings.xml](https://developer.android.com/guide/topics/resources/localization#move-strings-xml).
This should fix this issue. Thanks for reporting! 👍

**Comment by CrazyMarvin** [comment]
> We will put all strings into /app/src/main/res/values/[strings.xml](https://developer.android.com/guide/topics/resources/localization#move-strings-xml).
> This should fix this issue. Thanks for reporting! 👍

Done. 👌
