### ISSUE TITLE
Missing strings in translation

### ISSUE THREAD

**Issue by comradekingu** [Crazy-Marvin/VacationDays#23]
@CrazyMarvin 
Added screenshots https://hosted.weblate.org/screenshots/vacation-days/vacation-days/
but a lot of those strings aren't in
https://hosted.weblate.org/zen/vacation-days/vacation-days/en/?q=

Only those in https://github.com/Crazy-Marvin/VacationDays/blob/development/app/src/main/res/values/strings.xml are present, and everything in
https://github.com/Crazy-Marvin/VacationDays/blob/aa33f7df3605b69a1d1c6638abd561311cdcbef2/app/src/main/res/layout/activity_settings.xml
is missing?

Can the latter strings be added to the former?

**Comment by CrazyMarvin** [comment]
Hey @comradekingu,
thank you so much!
All strings should be on Weblate now. We put all strings in the strings.xml so that they are in one place as recommended.
