### ISSUE TITLE
Use of All files access (MANAGE_EXTERNAL_STORAGE) permission

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/VacationDays#29]
The app offers a backup feature. Is there an option to save it on the device and keep it after uninstalling the backup without using this [permission](https://support.google.com/googleplay/android-developer/answer/10467955?hl=en&visit_id=637827227701244456-1173491181&rd=1)?

**Comment by unbiaseduser** [comment]
@arafaatqureshi can you close this issue now?
