### ISSUE TITLE
Google Play and F-Droid links resulting in a 404 error.

### ISSUE THREAD

**Issue by paulaime** [Crazy-Marvin/VacationDays#34]
The Google Play and F-Droid links on this GitHub repo and on the website result in a 404 error.
Was the app removed from these stores?

**Comment by CrazyMarvin** [comment]
The app is under review at the moment.
I will let you know once it is approved.

**Comment by CrazyMarvin** [comment]
Google just approved the app.
I suppose F-Droid will follow soon.

**Comment by CrazyMarvin** [comment]
The links are working now. 🎉
