### ISSUE TITLE
Theme not working

### ISSUE THREAD

**Issue by gdonisi** [Crazy-Marvin/VacationDays#47]
## :writing_hand: Describe the bug
The app theme is not saving

## :bomb: Steps to reproduce
1. Go to Settings
2. Click on Appearance
3. Choose your theme
4. Restart the app

## :wrench: Expected behavior
The theme is saved and applied

## :camera: Screenshots

https://user-images.githubusercontent.com/82442402/162721844-3c33d39a-ae4f-478e-bfea-4f7c4438c5c5.mp4

## :iphone: Tech info
Xiaomi Mi 9T, Arrow OS Android 12

**Comment by CrazyMarvin** [comment]
Thanks for the info.
I am able to reproduce this issue.
@arafaatqureshi, may you have a look please?

**Comment by arafaatqureshi** [comment]
@CrazyMarvin noted, will fix it and update the code.

**Comment by amarradi** [comment]
Its solved?

**Comment by arafaatqureshi** [comment]
@amarradi @CrazyMarvin  i'm on it. it works with a few devices . will push the update soon.

**Comment by amarradi** [comment]
Oh cool, I have implemented this for my app as well. Just let me know if you need help or check out my code. It works for me for all devices

**Comment by arafaatqureshi** [comment]
Theme issue#47 fixed
