### ISSUE TITLE
Icon in dark Theme is not visible 

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#59]
In dark mode 2 icons are not visible

See the screenshot. You have to copy the icons in the -night folder

![Screenshot_20220722-100006.png](https://user-images.githubusercontent.com/720573/180393248-09e594ff-6ba3-4e91-9373-6798b8401f2e.png)

![Screenshot_20220722-100256.png](https://user-images.githubusercontent.com/720573/180393270-9027e7d1-b32b-4787-8c8c-77c2f534a6da.png)

**Comment by CrazyMarvin** [comment]
Thanks for noticing this. 👍
Are you available to fix this (and maybe https://github.com/Crazy-Marvin/VacationDays/issues/60)?

**Comment by amarradi** [comment]
Hey,

Ja das ist kein Problem. Yes thats no Problem, but Not today we are
planning our holiday

Mein Krebstagebuch: https://www.marcusradisch.de

CrazyMarvin ***@***.***> schrieb am Fr., 22. Juli 2022, 10:41:

**Comment by amarradi** [comment]
i tried to checkout an new branch but i need the permission, that i can push to you and you can merge it.

**Comment by CrazyMarvin** [comment]
> i tried to checkout an new branch but i need the permission, that i can push to you and you can merge it.

To which branch did you try to push? The **trunk** (master branch) is protected but the default branch **development** should work.

**Comment by CrazyMarvin** [comment]
For a pull request (PR) you have to make the changes in your own copy/fork and from there you can open a PR to this repository. Check [this](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) for more info.

**Comment by amarradi** [comment]
[marcus@thinkpad VacationDays]$ git push origin development
remote: Permission to Crazy-Marvin/VacationDays.git denied to amarradi.
fatal: konnte nicht auf 'https://github.com/Crazy-Marvin/VacationDays/' zugreifen: The requested URL returned error: 403

The Errormessage

**Comment by CrazyMarvin** [comment]
OK, I will give you the permission for now. 
But the usual process would be to do a fork (it would appear in your account like https://github.com/amarradi/VacationDays) and a PR afterwards.

**Comment by CrazyMarvin** [comment]
You may accept the invitation and try to push again. 👌

**Comment by amarradi** [comment]
It is ready you can remove the write permissions again

**Comment by CrazyMarvin** [comment]
Thank you very much for your help! 👍

**Comment by amarradi** [comment]
When will you release a final version?

**Comment by CrazyMarvin** [comment]
> When will you release a final version?

This weekend I suppose. I would like to include the fix for #47 too.
