### ISSUE TITLE
Switch to Vector Graphics

### ISSUE THREAD

**Issue by CrazyMarvin** [Crazy-Marvin/VacationDays#60]
Vector graphics offer a higher resolution and are smaller than raster graphics.  
I think using vector graphics instead of the raster graphics have positive effects only and no  downsides.
Let me know if you see any issues with this though of which I am currently unaware of.

**Comment by CrazyMarvin** [comment]
Vector graphics may be exported directly from [Figma](https://www.figma.com/file/9Fk92SQVItIwAjVfsakopo/), [Feather Icons](https://feathericons.com/) or downloaded from [here](https://github.com/Crazy-Marvin/VacationDays/files/9166235/vectors.zip).

**Comment by CrazyMarvin** [comment]
@amarradi may work on this. 🎉

**Comment by amarradi** [comment]
If you please give me write permissions, I can push the branch and you can merge it

**Comment by CrazyMarvin** [comment]
Done in 7767119484a0cc4a6c92b809bf3bbd4d94d417ae by @amarradi.
Thank you very much for your help! 😘
