### ISSUE TITLE
Versionname

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#74]
![Screenshot_20220812-185406.png](https://user-images.githubusercontent.com/720573/184411411-aff58b91-666d-4f4f-a883-e6d602f8b64c.png)

**Comment by CrazyMarvin** [comment]
May you prepare a fix for this please?

**Comment by CrazyMarvin** [comment]
I just noticed that the strings for **About** and **Settings** are hard-coded in the menu. Can you fix that too please?

https://github.com/Crazy-Marvin/VacationDays/blob/development/app/src/main/res/menu/side_menu.xml#L12

**Comment by amarradi** [comment]
Het Marvin,

Yes i think thats no great thing. We are going home today so I can do this
next week

Marcus

Mein Krebstagebuch: https://www.marcusradisch.de

CrazyMarvin ***@***.***> schrieb am Sa., 13. Aug. 2022, 00:51:

**Comment by amarradi** [comment]
`  @SuppressLint({"StringFormatInvalid", "LocalSuppress"}) String version =
                String.format(getResources().getString(R.string.version),
                BuildConfig.VERSION_NAME);
        appVersion.setText(version);`

Does anyone have an idea why I see 1.0 instead of 7.0. In the build.gradle under Version_Name it says "7.0".

`android {
    compileSdkVersion 32
    defaultConfig {
        applicationId "rocks.poopjournal.vacationdays"
        minSdkVersion 21
        targetSdkVersion 31
        versionCode 7
        versionName "7.0"`

**Comment by amarradi** [comment]
In my app the pancake counter it runs error free since the first version

**Comment by CrazyMarvin** [comment]
> `  @SuppressLint({"StringFormatInvalid", "LocalSuppress"}) String version =
>                 String.format(getResources().getString(R.string.version),
>                 BuildConfig.VERSION_NAME);
>         appVersion.setText(version);`
> 
> Does anyone have an idea why I see 1.0 instead of 7.0. In the build.gradle under Version_Name it says "7.0".
> 
> `android {
>     compileSdkVersion 32
>     defaultConfig {
>         applicationId "rocks.poopjournal.vacationdays"
>         minSdkVersion 21
>         targetSdkVersion 31
>         versionCode 7
>         versionName "7.0"`

I don't know. 😅
@arafaatqureshi, may you help us please?

**Comment by CrazyMarvin** [comment]
> In my app the pancake counter it runs error free since the first version

What do you mean, @amarradi? 🤔

**Comment by amarradi** [comment]
I have adapted the code for the version display from my app on the vacationDays. But I see only version 1.0 but not 7.0 as defined in build.gradle 

I'm sure there's another trap I don't know about. Actually the buildConfig.VERSION_NAME shows the versionName. At least that's what I thought. But it does not run.

**Comment by unbiaseduser** [comment]
Erm... You're importing a library's buildconfig instead of your app's.
`import com.github.sundeepk.compactcalendarview.BuildConfig;`
Just remove that line and rebuild the app (just to be sure) and the app will display the correct version.

**Comment by amarradi** [comment]
@unbiaseduser

Thank you for your help. Now I have recovered from the monthly chemo and was able to adjust the source text accordingly. It runs. Thanks

**Comment by CrazyMarvin** [comment]
Thank you so much and all the best for you.
