### ISSUE TITLE
IT Crashes in Android 9

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#92]
On Android 9 it Crashes Version 8.0

**Comment by amarradi** [comment]
Reset and delete Data solved this Problem bur i lose my data

**Comment by CrazyMarvin** [comment]
Oh no, that are bad news. 😬
Do you have an idea, @arafaatqureshi?

**Comment by amarradi** [comment]
I had a similar problem with sharedPreferences. I have extended these with
certain values. After that, the app blew up in my face. I found out that
you don't actually lose data when you update. Unfortunately, stackoverflow
doesn't give a good answer and neither does Google itself, except that you
should solve everything with databases. You can't really test it, because
the app is only defective after the update. It would be worth checking
whether it generally crashes after the update, i.e. also an app without
created values or only when values are in it.

CrazyMarvin ***@***.***> schrieb am Mo., 12. Sep. 2022, 19:48:

**Comment by CrazyMarvin** [comment]
It should be fixed by now.
