### ISSUE TITLE
Missing spaces

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#98]
Maybe a line break is not so bad either, or as a small table. I'm not very good at graphics, but the space is missing.

![Screenshot_20220923-153517~2.png](https://user-images.githubusercontent.com/720573/191973044-eb3f6278-0e46-4bb8-848b-794dee16f9c0.png)

**Comment by CrazyMarvin** [comment]
The text will be replaced with icons. You may see that in the [mockup on Figma](https://www.figma.com/file/9Fk92SQVItIwAjVfsakopo/Vacation-Days). The text will be used as [`android:contentDescription`](https://developer.android.com/reference/android/view/View#attr_android:contentDescription) for users with impairments (e.g. blind users). @arafaatqureshi will finish it soon and it will be updated in the next release.

**Comment by arafaatqureshi** [comment]
@amarradi this was just the functionality check, will be replaced with the icons and contentDescription in the next push InshaAllah.

**Comment by amarradi** [comment]
Ah okay i understand
