### ISSUE TITLE
Choose time span with tap an drag

### ISSUE THREAD

**Issue by amarradi** [Crazy-Marvin/VacationDays#99]
I intuitively clicked on the date and dragged my finger to the end date. But that did not work.
When I click on the date, the start date is set. Now I click on the next date and the end date is set. That is correct. Is there a possibility to set the date with a time span? I press the start date and drag to the end date and then release?

**Comment by unbiaseduser** [comment]
Google's date picker library doesn't support dragging, if you want it you can [ask them.](https://github.com/material-components/material-components-android/issues)

**Comment by amarradi** [comment]
On Material.io it looks like this tap and drag is supported

https://material.io/components/date-pickers

Therefore I had the idea that it could be nice to realize it

Mein Krebstagebuch  https://www.marcusradisch.de

unbiaseduser ***@***.***> schrieb am Mo., 26. Sep. 2022,
05:19:

**Comment by unbiaseduser** [comment]
I'm 100% sure they specifically say:
> To select a range of dates, tap the start and end dates on the calendar

**Comment by amarradi** [comment]
Ah I just see that this cool feature exists in the Material Design for the
desktop datepicker. Apparently there's not for the mobile variant. I find
this stupid, but my opinion is not important for Google.

Mein Krebstagebuch  https://www.marcusradisch.de

unbiaseduser ***@***.***> schrieb am Mo., 26. Sep. 2022,
06:53:

**Comment by CrazyMarvin** [comment]
I will close this then.
